name: Deploy-workflow
on:
  push:
    branches:
      - main
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Pyhton
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run-tests
        run: pytest ./test/test_helpers.py
