name: Deploy-workflow
on:
  push:
    branches:
      - main
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: export pythonpath
        run: export PYTHONPATH=$(pwd)
      - name: run-tests
        run: pytest ./test/test_helpers.py
  deploy-to-aws:
    name: deploy
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - uses: hashicorp/setup-terraform@v3
      - run: cd terraform
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
